name: Remote deploy code documentation

on:
  push:
    branches: ["dev", "main"]

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y binutils coreutils desktop-file-utils fakeroot fuse libgdk-pixbuf2.0-dev patchelf python3-pip python3-setuptools squashfs-tools strace util-linux zsync libgtk-3-dev
      - name: Cargo doc
        run: cargo doc
      - name: Deploy docs
        uses: appleboy/scp-action@v0.1.4
        with:
          source: "target/doc/*"
          target: "/var/www/html/config_app/${{ env.BRANCH_NAME }}"
          username: ${{ secrets.USER }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          rm: true

